services:
  mysql:
    build:
        dockerfile: Dockerfile.dev
    container_name: vsa_journey-mysql
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin@vsa_journey
      - MYSQL_DATABASE=vsa_journey-db
      - MYSQL_ROOT_PASSWORD=admin@vsa_journey
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  
  papercut:
    image: changemakerstudiosus/papercut-smtp:latest
    container_name: vsa_journey-papercut
    ports:
      - "8080:80"
      - "25:25"
  
volumes:
  mysql_data:
    driver: local